import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    dashboard: 'Smart IoT Agriculture Dashboard',
    soilMoisture: 'Soil Moisture',
    phLevel: 'pH Level',
    waterPump: 'Water Pump',
    diseaseAnalysis: 'Disease Analysis',
    analyzeImage: 'Analyze Image',
    settings: 'Settings',
    blynkToken: 'Blynk Auth Token',
    n8nWebhook: 'n8n Webhook URL',
    status: 'Status',
    on: 'ON',
    off: 'OFF',
    loading: 'Processing...',
    uploadImage: 'Upload Leaf Image',
    analysisResult: 'Analysis Result',
    language: 'Language',
    customerSupport: 'Customer Support',
    logout: 'Logout',
    cropRecommendation: 'Crop Recommendation',
    getRecommendation: 'Get Recommendation',
    analyzingData: 'Analyzing Farm Data...',
    recommendedCrops: 'Recommended Crops',
    location: 'Location',
    unknown: 'Unknown',
    month: 'Month',
    listen: 'Listen',
  },
  hi: {
    dashboard: 'स्मार्ट आईओटी कृषि डैशबोर्ड',
    soilMoisture: 'मिट्टी की नमी',
    phLevel: 'पीएच स्तर',
    waterPump: 'पानी का पंप',
    diseaseAnalysis: 'रोग विश्लेषण',
    analyzeImage: 'छवि का विश्लेषण करें',
    settings: 'सेटिंग्स',
    blynkToken: 'ब्लिंक ऑथ टोकन',
    n8nWebhook: 'n8n वेबहुक URL',
    status: 'स्थिति',
    on: 'चालू',
    off: 'बंद',
    loading: 'प्रसंस्करण...',
    uploadImage: 'पत्ती की छवि अपलोड करें',
    analysisResult: 'विश्लेषण परिणाम',
    language: 'भाषा',
    customerSupport: 'ग्राहक सहायता',
    logout: 'लॉगआउट',
    cropRecommendation: 'फसल की सिफारिश',
    getRecommendation: 'सिफारिश प्राप्त करें',
    analyzingData: 'खेत के आंकड़ों का विश्लेषण...',
    recommendedCrops: 'अनुशंसित फसलें',
    location: 'स्थान',
    unknown: 'अज्ञात',
    month: 'महीना',
    listen: 'सुनें',
  },
  mr: {
    dashboard: 'स्मार्ट आयओटी कृषी डॅशबोर्ड',
    soilMoisture: 'मातीतील ओलावा',
    phLevel: 'पीएच पातळी',
    waterPump: 'पाण्याचा पंप',
    diseaseAnalysis: 'रोग विश्लेषण',
    analyzeImage: 'प्रतिमेचे विश्लेषण करा',
    settings: 'सेटिंग्ज',
    blynkToken: 'ब्लिंक ऑथ टोकन',
    n8nWebhook: 'n8n वेबहुक URL',
    status: 'स्थिती',
    on: 'चालू',
    off: 'बंद',
    loading: 'प्रक्रिया सुरू आहे...',
    uploadImage: 'पानाचे चित्र अपलोड करा',
    analysisResult: 'विश्लेषण निकाल',
    language: 'भाषा',
    customerSupport: 'ग्राहक समर्थन',
    logout: 'लॉगआउट',
    cropRecommendation: 'पीक शिफारस',
    getRecommendation: 'शिफारस मिळवा',
    analyzingData: 'शेती डेटाचे विश्लेषण करत आहे...',
    recommendedCrops: 'शिफारस केलेली पिके',
    location: 'स्थान',
    unknown: 'अज्ञात',
    month: 'महिना',
    listen: 'ऐका',
  },
  te: {
    dashboard: 'స్మార్ట్ ఐఓటి అగ్రికల్చర్ డాష్‌బోర్డ్',
    soilMoisture: 'నేల తేమ',
    phLevel: 'pH స్థాయి',
    waterPump: 'నీటి పంపు',
    diseaseAnalysis: 'వ్యాధి విశ్లేషణ',
    analyzeImage: 'చిత్రాన్ని విశ్లేషించండి',
    settings: 'సెట్టింగ్లు',
    blynkToken: 'బ్లింక్ ఆథ్ టోకెన్',
    n8nWebhook: 'n8n వెబ్‌హుక్ URL',
    status: 'స్థితి',
    on: 'ఆన్',
    off: 'ఆఫ్',
    loading: 'ప్రాసెస్ అవుతోంది...',
    uploadImage: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    analysisResult: 'విశ్లేషణ ఫలితం',
    language: 'భాష',
    customerSupport: 'కస్టమర్ సపోర్ట్',
    logout: 'లాగ్అవుట్',
    cropRecommendation: 'పంట సిఫార్సు',
    getRecommendation: 'సిఫార్సు పొందండి',
    analyzingData: 'ఫామ్ డేటాను విశ్లేషిస్తోంది...',
    recommendedCrops: 'సిఫార్సు చేయబడిన పంటలు',
    location: 'స్థానం',
    unknown: 'తెలియదు',
    month: 'నెల',
    listen: 'వినండి',
  },
  ta: {
    dashboard: 'ஸ்மார்ட் ஐஓடி விவசாய டாஷ்போர்டு',
    soilMoisture: 'மண் ஈரப்பதம்',
    phLevel: 'pH அளவு',
    waterPump: 'தண்ணீர் பம்ப்',
    diseaseAnalysis: 'நோய் பகுப்பாய்வு',
    analyzeImage: 'படத்தை பகுப்பாய்வு செய்',
    settings: 'அமைப்புகள்',
    blynkToken: 'பிளிங்க் அங்கீகார டோக்கன்',
    n8nWebhook: 'n8n வெப்ஹூக் URL',
    status: 'நிலை',
    on: 'ஆன்',
    off: 'ஆஃப்',
    loading: 'செயலாக்கப்படுகிறது...',
    uploadImage: 'இலை படத்தை பதிவேற்றவும்',
    analysisResult: 'பகுப்பாய்வு முடிவு',
    language: 'மொழி',
    customerSupport: 'வாடிக்கையாளர் ஆதரவு',
    logout: 'வெளியேறு',
    cropRecommendation: 'பயிர் பரிந்துரை',
    getRecommendation: 'பரிந்துரை பெறவும்',
    analyzingData: 'பண்ணை தரவை பகுப்பாய்வு செய்கிறது...',
    recommendedCrops: 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    location: 'இடம்',
    unknown: 'தெரியவில்லை',
    month: 'மாதம்',
    listen: 'கேளுங்கள்',
  },
  kn: {
    dashboard: 'ಸ್ಮಾರ್ಟ್ ಐಓಟಿ ಕೃಷಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    soilMoisture: 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
    phLevel: 'pH ಮಟ್ಟ',
    waterPump: 'ನೀರಿನ ಪಂಪ್',
    diseaseAnalysis: 'ರೋಗ ವಿಶ್ಲೇಷಣೆ',
    analyzeImage: 'ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    blynkToken: 'ಬ್ಲಿಂಕ್ ಆಥ್ ಟೋಕನ್',
    n8nWebhook: 'n8n ವೆಬ್‌ಹುಕ್ URL',
    status: 'ಸ್ಥಿತಿ',
    on: 'ಆನ್',
    off: 'ಆಫ್',
    loading: 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    uploadImage: 'ಎಲೆ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    analysisResult: 'ವಿಶ್ಲೇಷಣೆಯ ಫಲಿತಾಂಶ',
    language: 'ಭಾಷೆ',
    customerSupport: 'ಗ್ರಾಹಕ ಬೆಂಬಲ',
    logout: 'ಲಾಗ್‌ಔಟ್',
    cropRecommendation: 'ಬೆಳೆ ಶಿಫಾರಸು',
    getRecommendation: 'ಶಿಫಾರಸು ಪಡೆಯಿರಿ',
    analyzingData: 'ಫಾರ್ಮ್ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    recommendedCrops: 'ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆಗಳು',
    location: 'ಸ್ಥಳ',
    unknown: 'ಅಜ್ಞಾತ',
    month: 'ತಿಂಗಳು',
    listen: 'ಕೇಳಿ',
  },
  gu: {
    dashboard: 'સ્માર્ટ આઈઓટી કૃષિ ડેશબોર્ડ',
    soilMoisture: 'જમીનમાં ભેજ',
    phLevel: 'pH સ્તર',
    waterPump: 'પાણીનો પંપ',
    diseaseAnalysis: 'રોગ વિશ્લેષણ',
    analyzeImage: 'છબીનું વિશ્લેષણ કરો',
    settings: 'સેટિંગ્સ',
    blynkToken: 'બ્લિંક ઓથ ટોકન',
    n8nWebhook: 'n8n વેબહૂક URL',
    status: 'સ્થિતિ',
    on: 'ચાલુ',
    off: 'બંધ',
    loading: 'પ્રક્રિયા થઈ રહી છે...',
    uploadImage: 'પાનની છબી અપલોડ કરો',
    analysisResult: 'વિશ્લેષણ પરિણામ',
    language: 'ભાષા',
    customerSupport: 'ગ્રાહક સપોર્ટ',
    logout: 'લોગઆઉટ',
    cropRecommendation: 'પાકની ભલામણ',
    getRecommendation: 'ભલામણ મેળવો',
    analyzingData: 'ફાર્મ ડેટાનું વિશ્લેષણ કરી રહ્યું છે...',
    recommendedCrops: 'ભલામણ કરેલ પાક',
    location: 'સ્થાન',
    unknown: 'અજ્ઞાત',
    month: 'મહિનો',
    listen: 'સાંભળો',
  },
  bn: {
    dashboard: 'স্মার্ট আইওটি কৃষি ড্যাশবোর্ড',
    soilMoisture: 'মাটির আর্দ্রতা',
    phLevel: 'pH স্তর',
    waterPump: 'জলের পাম্প',
    diseaseAnalysis: 'রোগ বিশ্লেষণ',
    analyzeImage: 'ছবি বিশ্লেষণ করুন',
    settings: 'সেটিংস',
    blynkToken: 'ব্লিঙ্ক অথ টোকেন',
    n8nWebhook: 'n8n ওয়েবহুক URL',
    status: 'অবস্থা',
    on: 'চালু',
    off: 'বন্ধ',
    loading: 'প্রক্রিয়াকরণ হচ্ছে...',
    uploadImage: 'পাতার ছবি আপলোড করুন',
    analysisResult: 'বিশ্লেষণ ফলাফল',
    language: 'ভাষা',
    customerSupport: 'গ্রাহক সহায়তা',
    logout: 'লগআউট',
    cropRecommendation: 'ফসল সুপারিশ',
    getRecommendation: 'সুপারিশ পান',
    analyzingData: 'খামারের তথ্য বিশ্লেষণ করা হচ্ছে...',
    recommendedCrops: 'প্রস্তাবিত ফসল',
    location: 'অবস্থান',
    unknown: 'অজানা',
    month: 'মাস',
    listen: 'শুনুন',
  },
  pa: {
    dashboard: 'ਸਮਾਰਟ ਆਈਓਟੀ ਖੇਤੀਬਾੜੀ ਡੈਸ਼ਬੋਰਡ',
    soilMoisture: 'ਮਿੱਟੀ ਦੀ ਨਮੀ',
    phLevel: 'pH ਪੱਧਰ',
    waterPump: 'ਪਾਣੀ ਦਾ ਪੰਪ',
    diseaseAnalysis: 'ਬਿਮਾਰੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    analyzeImage: 'ਚਿੱਤਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    blynkToken: 'ਬਲਿੰਕ ਔਥ ਟੋਕਨ',
    n8nWebhook: 'n8n ਵੈਬਹੁੱਕ URL',
    status: 'ਸਥਿਤੀ',
    on: 'ਚਾਲੂ',
    off: 'ਬੰਦ',
    loading: 'ਪ੍ਰੋਸੈਸਿੰਗ ਹੋ ਰਹੀ ਹੈ...',
    uploadImage: 'ਪੱਤੇ ਦੀ ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ',
    analysisResult: 'ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜਾ',
    language: 'ਭਾਸ਼ਾ',
    customerSupport: 'ਗਾਹਕ ਸਹਾਇਤਾ',
    logout: 'ਲੌਗਆਉਟ',
    cropRecommendation: 'ਫਸਲ ਦੀ ਸਿਫਾਰਸ਼',
    getRecommendation: 'ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
    analyzingData: 'ਫਾਰਮ ਡੇਟਾ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    recommendedCrops: 'ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਫਸਲਾਂ',
    location: 'ਸਥਾਨ',
    unknown: 'ਅਣਜਾਣ',
    month: 'ਮਹੀਨਾ',
    listen: 'ਸੁਣੋ',
  },
  ml: {
    dashboard: 'സ്മാർട്ട് ഐഒടി അഗ്രികൾച്ചർ ഡാഷ്‌ബോർഡ്',
    soilMoisture: 'മണ്ണിലെ ഈർപ്പം',
    phLevel: 'pH നില',
    waterPump: 'വാട്ടർ പമ്പ്',
    diseaseAnalysis: 'രോഗ വിശകലനം',
    analyzeImage: 'ചിത്രം വിശകലനം ചെയ്യുക',
    settings: 'ക്രമീകരണങ്ങൾ',
    blynkToken: 'ബ്ലിങ്ക് ഓത്ത് ടോക്കൺ',
    n8nWebhook: 'n8n വെബ്ഹുക്ക് URL',
    status: 'നില',
    on: 'ഓൺ',
    off: 'ഓഫ്',
    loading: 'പ്രോസസ്സ് ചെയ്യുന്നു...',
    uploadImage: 'ഇലയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    analysisResult: 'വിശകലന ഫലം',
    language: 'ഭാഷ',
    customerSupport: 'കസ്റ്റമർ സപ്പോർട്ട്',
    logout: 'ലോഗൗട്ട്',
    cropRecommendation: 'വിള ശുപാർശ',
    getRecommendation: 'ശുപാർശ നേടുക',
    analyzingData: 'ഫാം ഡാറ്റ വിശകലനം ചെയ്യുന്നു...',
    recommendedCrops: 'ശുപാർശ ചെയ്യുന്ന വിളകൾ',
    location: 'സ്ഥലം',
    unknown: 'അജ്ഞാതം',
    month: 'മാസം',
    listen: 'കേൾക്കുക',
  },
  es: {
    dashboard: 'Panel de Agricultura Smart IoT',
    soilMoisture: 'Humedad del Suelo',
    phLevel: 'Nivel de pH',
    waterPump: 'Bomba de Agua',
    diseaseAnalysis: 'Análisis de Enfermedades',
    analyzeImage: 'Analizar Imagen',
    settings: 'Ajustes',
    blynkToken: 'Token de Blynk',
    n8nWebhook: 'URL de n8n',
    status: 'Estado',
    on: 'ENCENDIDO',
    off: 'APAGADO',
    loading: 'Procesando...',
    uploadImage: 'Subir Imagen de Hoja',
    analysisResult: 'Resultado del Análisis',
    language: 'Idioma',
    customerSupport: 'Soporte al Cliente',
    logout: 'Cerrar Sesión',
    cropRecommendation: 'Recomendación de Cultivos',
    getRecommendation: 'Obtener Recomendación',
    analyzingData: 'Analizando Datos de la Granja...',
    recommendedCrops: 'Cultivos Recomendados',
    location: 'Ubicación',
    unknown: 'Desconocido',
    month: 'Mes',
    listen: 'Escuchar',
  },
  fr: {
    dashboard: 'Tableau Agriculture Smart IoT',
    soilMoisture: 'Humidité du Sol',
    phLevel: 'Niveau de pH',
    waterPump: 'Pompe à Eau',
    diseaseAnalysis: 'Analyse des Maladies',
    analyzeImage: 'Analyser l\'Image',
    settings: 'Paramètres',
    blynkToken: 'Jeton Blynk',
    n8nWebhook: 'URL n8n',
    status: 'Statut',
    on: 'MARCHE',
    off: 'ARRÊT',
    loading: 'Traitement...',
    uploadImage: 'Télécharger l\'Image de la Feuille',
    analysisResult: 'Résultat de l\'Analyse',
    language: 'Langue',
    customerSupport: 'Support Client',
    logout: 'Déconnexion',
    cropRecommendation: 'Recommandation de Culture',
    getRecommendation: 'Obtenir une Recommandation',
    analyzingData: 'Analyse des Données de la Ferme...',
    recommendedCrops: 'Cultures Recommandées',
    location: 'Emplacement',
    unknown: 'Inconnu',
    month: 'Mois',
    listen: 'Écouter',
  },
};
